export const ProductList =  [
  {
    id: "1",
    title: "The Little Mermaid - 4K Blu-Ray",
    description: "Blu-Ray en formato 4K",
    price: 2500,
    image: "little-mermaid.png",
    stock: 3,
    categoryId: "peliculas",
  },
  {
    id: "2",
    title: "Beauty and the Beast - 4K Blu-Ray",
    description: "Blu-Ray en formato 4K",
    price: 2700,
    image: "beauty-beast.png",
    stock: 4,
    categoryId: "peliculas",
  },
  {
    id: "3",
    title: "The Lion King - 4K Blu-Ray",
    description: "Blu-Ray en formato 4K",
    price: 2800,
    image: "lion-king.png",
    stock: 5,
    categoryId: "peliculas",
  },
  {
    id: "4",
    title: "Aladdin - 4K Blu-Ray",
    description: "Blu-Ray en formato 4K",
    price: 2500,
    image: "aladdin.png",
    stock: 3,
    categoryId: "peliculas",
  },
  {
    id: "5",
    title: "Muñeco Woody - Toy Story",
    description: "Muñeco coleccionable",
    price: 4500,
    image: "woody.png",
    stock: 6,
    categoryId: "merchandising",
  },
  {
    id: "6",
    title: "Taza Chip - Beauty and the Beast",
    description: "Taza de la película",
    price: 1200,
    image: "chip.png",
    stock: 2,
    categoryId: "merchandising",
  },
  {
    id: "7",
    title: "Sombrero Mickey - Walt Disney World",
    description: "Muñeco coleccionable",
    price: 4500,
    image: "mickey-hat.png",
    stock: 4,
    categoryId: "merchandising",
  },
  {
    id: "8",
    title: "Globo de Nieve - Mickey",
    description: "Muñeco coleccionable",
    price: 4500,
    image: "globe.png",
    stock: 4,
    categoryId: "merchandising",
  },
  {
    id: "9",
    title: "Entradas Magic Kingdom",
    description: "Válidas para el día de hoy",
    price: 12500,
    image: "magic-kingdom.png",
    stock: 3,
    categoryId: "parques",
  },
  {
    id: "10",
    title: "Entradas Hollywood Studios",
    description: "Válidas para el día de hoy",
    price: 10500,
    image: "hollywood-studios.png",
    stock: 5,
    categoryId: "parques",
  },
  {
    id: "11",
    title: "Entradas Animal Kingdom",
    description: "Válidas para el día de hoy",
    price: 9500,
    image: "animal-kingdom.png",
    stock: 4,
    categoryId: "parques",
  },
  {
    id: "12",
    title: "Entradas Epcot",
    description: "Válidas para el día de hoy",
    price: 8500,
    image: "epcot.png",
    stock: 8,
    categoryId: "parques",
  },
];
